todo/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView

app_name = "accounts"


urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("create/", RegisterView.as_view(), name='create')

]

todo/api_v1/urls.py
from django.urls import path, include, re_path
from api_v1.views import TaskView, TaskDetail, TaskExecute


app_name = "api_v1"

urlpatterns = [

   path('tasks/', TaskView.as_view()),
   path('tasks/<int:pk>/', TaskDetail.as_view()),
   path('tasks/<int:pk>/execute/', TaskExecute.as_view()),
   path('auth/', include('djoser.urls')),
   re_path(r'^auth/', include('djoser.urls.authtoken')),

]

todo/source/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

api_urls = [
    path('v1/', include("api_v1.urls"))
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts', include("accounts.urls")),
    path('api/', include(api_urls))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/webapp/urls.py
from django.contrib import admin
from django.urls import path

from webapp.views.tasks import IndexView

app_name = "webapp"

urlpatterns = [
    path("", IndexView.as_view(), name="index")

]

todo/accounts/models.py
from django.db import models

# Create your models here.

todo/api_v1/models.py
from django.db import models

# Create your models here.

todo/webapp/models.py
from django.db import models

# Create your models here.


class Task(models.Model):
    title = models.CharField(max_length=100, null=False, blank=False, verbose_name="Заголовок")
    description = models.TextField(max_length=3000, verbose_name="Описание")
    deadline = models.DateTimeField(verbose_name="Срок выполнения")
    performed = models.BooleanField(default=False, verbose_name="Выполнено/Не выполнено")

    def __str__(self):
        return f"{self.id}. {self.title}: {self.description}.{self.performed}"

    class Meta:
        db_table = "tasks"
        verbose_name = "Задача"
        verbose_name_plural = "Задачи"

todo/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        fields = ['email', 'password1', 'password2']

todo/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import make_password


# Create your views here.
from django.urls import reverse
from django.views.generic import CreateView
from accounts.forms import MyUserCreationForm


class RegisterView(CreateView):
    model = User
    template_name = 'user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        email = self.request.POST.get("email")
        password = self.request.POST.get("password")
        user = User.objects.create_user(username=email, email=email, password=make_password(password))
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:index')
        return next_url


def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('webapp:index')
        else:
            context['has_error'] = True
    return render(request, 'login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:index')

todo/api_v1/views.py
from rest_framework.response import Response
from rest_framework.generics import get_object_or_404
from rest_framework.views import APIView

# Create your views here.
from webapp.models import Task
from api_v1.serializers import TaskModelsSerializer, TaskAllModelsSerializer, TaskCreatModelsSerializer
from rest_framework.permissions import IsAuthenticated


class TaskView(APIView):
    serializer_class = TaskCreatModelsSerializer
    permission_classes = (IsAuthenticated,)

    def get(self, request, *args, **kwargs):
        tasks = Task.objects.all()
        serializer_obj = TaskModelsSerializer(instance=tasks, many=True)
        return Response(serializer_obj.data)

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data, status=201)


class TaskDetail(APIView):
    serializer_class = TaskAllModelsSerializer
    permission_classes = (IsAuthenticated,)

    def get(self, request, *args, pk, **kwargs):
        try:
            task = Task.objects.get(pk=pk)
            task_data = self.serializer_class(task).data
            return Response(task_data)
        except:
            return Response({
                "message": "Task not found."
            }, status=404)

    def put(self, request, *args, pk, **kwargs):
        try:
            task = get_object_or_404(Task, pk=pk)
            serializer = self.serializer_class(data=request.data, instance=task)
            serializer.is_valid(raise_exception=True)
            serializer.save()
            return Response(serializer.data)
        except:
            return Response({
                "message": "Task not found."
            }, status=404)

    def delete(self, request, *args, pk, **kwargs):
        try:
            task = get_object_or_404(Task, pk=pk)
            task.delete()
            return Response({
                "message": "Task `{}` deleted.".format(pk)
            }, status=204)
        except:
            return Response({
                "message": "Task not found."
            }, status=404)


class TaskExecute(APIView):
    serializer_class = TaskAllModelsSerializer
    permission_classes = (IsAuthenticated,)

    def post(self, request, *args, pk, **kwargs):
        try:
            task = Task.objects.get(pk=pk)
            task.performed = True
            task.save()

            # Send email

            return Response({
                "message": "Task performed.".format(pk)
            }, status=204)
        except:
            return Response({
                "message": "Unable to update performed status"
            }, status=500)

todo/webapp/views/tasks.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView

from webapp.models import Task


class IndexView(ListView):
    model = Task
    template_name = "tasks/index.html"
    context_object_name = "tasks"

todo/accounts/templates/login.html
{% extends "base.html" %}
{% block title %}Вход{% endblock %}

{% block content %}
<div class="top_name card border-info mt-2 ms-4" style="max-width: 20rem;">
  <div class="card-header text-center"><h4>Вход</h4></div>
  <div class="card-body">
    <form method="post" class="text-center">
        {% csrf_token %}
        {% if has_error %}
            <p class="text-danger">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <br>
            <input type="password" name="password" id="password">
        </div>
        <br>
        <button class="btn btn-outline-info btn-sm" type="submit">Войти</button>
    </form>
  </div>
</div>
{% endblock %}

todo/accounts/templates/user_create.html
{% extends "base.html" %}
{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="top_name card border-info mt-2 ms-4" style="max-width: 20rem;">
    <div class="card-header text-center"><h4>Регистрация</h4></div>
    <div class="card-body">
        <form method="post">
            {% include 'partial/form.html' with button_text="Зарегистрироваться" %}
        </form>
    </div>
</div>
{% endblock %}

todo/webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}Главная{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'webapp:index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% block nav %}
                {% endblock %}
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Выйти</a>
                </li>
                    <li class="nav-item">
                        <p>Здравствуйте {{ user.username }}</p>
                    </li>
                {% else %}
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Вход</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:create' %}?next={{ request.get_full_path }}">Зарегистрироваться</a>
                </li>

                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}
        test
    {% endblock %}
</div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</html>

todo/webapp/templates/partial/form.html
{% csrf_token %}

{% for error in form.non_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}


{% for field in form %}
   <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
   {% for error in field.errors %}
       <p class="text-danger">{{ error }}</p>
   {% endfor %}
   <p>{{ field }}</p>
{% endfor %}

<input type="submit" value="{{ button_text }}"/>

todo/webapp/templates/tasks/index.html
{% extends "base.html" %}
{% load static %}

{% block nav %}

{% endblock %}

{% block content %}

<h1>Задачи</h1>

{% for task in tasks %}
    {{ task.title }}
    {{ task.description }}
    {{ task.deadline }}
    {{ task.performed }}
{% endfor %}

{% endblock %}